gui_audio_buttons.py

play and download buttons fully functional

Gui audio buttons

---

GUI.py
functions/addConventions.py
functions/diarizationAndTranscription.py
requirements.txt

Added functionality to grammar check process to add error coding to repeated words. There still exists a bug where inflectional morphemes are not added to some sentences with this type of coding.

Repeated words

---

functions/addConventions.py

In addInflectionalMorphemesToSentence(), each verb (and the word 'been') is checked to see if it's a 'to be' verb. Present participles generally require a preceding 'to be' verb, so this is checked whenever a 'VBG' is found to determing if /ing should be added (both gerunds and present participles are in the tagging category of VBG). isToBeVerb() was added to addConventions.py to help accomplish this task.

Added functionality to help distinguish gerunds from present participles in most cases.

---

guides/developerGuide.md
guides/userGuide.md
requirements.txt

A markdown guide has been created for developers, and one was also made for users.

User guides

---

guides/developerGuide.md
requirements.txt

Added information about the dependency spreadsheet to the developer guide.

Dependency licensing

---

guides/developerGuide.md
guides/userGuide.md
requirements.txt

Fixed comments in requirements.txt to use # instead of //. Also noted in developerGuide to run the pyinstaller command while in the directory with GUI.py

Requirements Comments

---

GUI.py

Fixes #70 
Added logic to allow for pausing/unpausing mid-playback, and reworked the Play button to consistently update with the start and stoppage of playback. Updated variable and method names to eliminate confusion and updated UI to utilize new functions.

Added Pause Button Functionality

---

GUI.py

After Travis implemented customTKinter to improve UI aesthetics, the functionality of most buttons needed to be changed to use the new library. The program should have full functionality, though visuals are not done yet. 
Fixes #82

Updates functionality of UI to work with customtkinter

---

testgui.py

Fixes #89
Added the new GUI layout into a dedicated file to accommodate a new file structure. 
Sections of the GUI were separated into various classes for organizational purposes.
To prevent the given GUI file from containing both software functionality and UI functionality, making it too long, separate files were needed for each. This is the beginning of that separation.

Adding new GUI layout base

---

.github/workflows/create-executable.yml
audio.py
functions/addConventions.py
guides/developerGuide.md
requirements.txt

Fixes #97 
I added a section in the developer guide called 'Python Version' that details the needed Python versions to successfully use our project. I tested many Python versions versions on my personal computer as well as consulting my team and tech lead to come up with the working Python versions that will run our project.
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I added documentation in guides/developerGuide.md. I added the 'Python Version' section. I did not change or remove anything else.
This was added because we did not have any documentation addressing the issue of only some Python versions being …

Added working Python version(s) documentation - FIXES #97

---

GUI.py
audio.py

Fixes #46
*Adjusted GUI to have an audio slider component. This came with lots of unexpected challenges, some of which are still not fixed*
*added for to improve the user experience so they can choose what spot in the audio to play instead of starting from the beginning every time*
*The files I modified were GUI.py and also audio.py because they interact in order to play audio. I figured this would be a matter of stopping the old audio stream and starting a new one, but either I am doing something wrong with that approach or it actually requires threading which I have started working on. There are some bugs that it introduces. At the moment, the audio starts playing from the selected point in time, but the previous …

starting to figure out audio slider

---

GUI.py
functions/addConventions.py

Fixes #113
*added lines that update the transcription box to the content within when grammar checking button is clicked*
*it was changed because it didn't make the changes that the end user requested which would be non functional*
*For now I just added 1 line " self.transcriptionText = self.transcriptionBox.get('1.0', "end")."*
I also changed the out of range error checking line on 240 by adding a +1 so that it won't be out of range.

Issue #113

---

README.md

Fixes #121 
In the MacOS executable instructions:
Changed dash to bullet point so that it matches the Windows executable instructions. I also now have fixed it so that it goes to roman numerals instead of numbers. This not only makes it match the Windows executable instructions, but it also allows the instructions below it to start from 1 instead of 3 so now it makes sense and does not look like a continuation of the MacOS executable instructions, so now that part is fixed as well.
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I changed the README.md file and made the bullet point formatting match. I also changed MacOS from numbers to roman …

Made Creating An Executable Instructions formatting match and numbered step formatting - FIXES #121

---

README.md

Fixes #132 
The README.md file was changed in multiple sections. It consisted of removing wordy unneeded sections and/or shortening some longer sections down as well as improving the structure/layout of the file.
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
README.md
It was redundant text and unnecessary.
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
Was not needed so I removed some sections and shortened others.
I removed text and shortened other sections. I also added some notes and small areas to sections where needed as described in there Issue …

Shortened up README.md file and fixed the layout #132

---

GUI.py
audio.py

Fixes #106 in progress
*removed the audio Playback area placeholder and put play and pause buttons there .*
*Changed because we needed to re-implement pause and play functionality*
*Just added buttons using the same format as the rest of the GUI*

Issue #106

---

.gitignore
GUI.py

Fixes #154
*I changed the GUI, specifically the play and pause/resume buttons. I added some new code for the purpose of rethreading and commented out some previous code.*
*Previously, there was an issue with some of the buttons not responding when clicked or needing to be clicked multiple times before responding. I made changes in order to improve this previously existing delay. Currently, the play button is responding well, from my device, and the pause button responds quickly, but when it shifts to resume, it does not respond.*
*In the GUI.py file, specifically within the playAudio and pauseAudio functions, I commented out some previously existing code. In its place, I wrote some lines which served to essentially …

Issue154 buttonresponsiveness

---

tests/data/input1.txt
tests/data/output1.txt
tests/saltify_test.py

Fixes #162 
*Edited the existing saltify_tests.py file. Added a new class containing two functions.*
*The two functions allow for us to compare the expected coded (transcribed) output to the generated coded output*
*Using an assertEqual statement in order to compare the expected coded output to the generated coded output, line by line, and as soon as a pair of lines are not equivalent, the test fails and lets us know that there is a discrepancy between the two files. Currently, need to add an update to the newly added test to allow for us to parse through multiple expected output files, rather than just one (also need to add these files to the tests folder). Also, there seems to be an issue with the diarizeAndTranscribe …

Issue162 testinfrastructure

---

DEVELOPER_GUIDE.md

Updated required Python version, to prevent developers from running into issue #160

Update python version in DEVELOPER_GUIDE.md

---

.github/workflows/create-executable.yml
.github/workflows/macos-build.yml
.github/workflows/windows-build.yml
.gitignore

Fixes #163 
Updated the workflow configuration to replace the deprecated "actions/upload-artifact@v2" with "actions/upload-artifact@v3."

testing v4 artifact

---

.github/workflows/macos-build.yml
.github/workflows/windows-build.yml

Issue same as #169 
FIxed by #172 
As a new user of the software I need an easy workflow for installing the dependencies, so working with the software is easy.
- [  ] Create a program that checks for required dependencies:
- [  ] The program will automatically verify if all necessary dependencies (e.g., Java, NLTK) are installed on the user's machine.
- [  ] Example:
- Check if Java is installed:
- If Java is not found, a pop-up will appear asking the user to install it.
- The pop-up will include a direct link to the official Java download page.
- After redirecting, the program can offer guidance or a prompt to install Java automatically.
- [  ] The program will skip the installation prompt for any dependencies that are already present on the user's system.

Issue169 dependency

---

GUI.py
audio.py
requirements.txt

Fixes #181 
*Modified the GUI.py file to include new buttons (forwards and backwards), also modified audio.py to include logic for implementation of scrubbing bar*
*We are trying to add new buttons and a scrubbing bar, so we need to change the current layout of our buttons.*
*I added new frames for the different features (transcribe, apply aliases, etc.) and moved the buttons into different frames according to matching functionality (moved play and pause to the same frame as upload and record audio). I also added buttons to allow for forwards and backwards, 5 seconds each, for enhanced functionality*

changing button layout to match new UI

---

.gitignore
GUI.py

Fixes #193 
*On the GUI, I added a new button, labelled "Help," which, when clicked, displays a guide describing the functionality of all the buttons on the GUI.*
*I added this feature because it will make the application for understandable and intuitive, especially for people who might be unfamiliar with all of its functions.*
*There were two main components I included in order to create this new feature. First, I created a new method in the GUI file which displays a Help Overlay, or guide screen. This function handles the creation of the help screen and all of the information on it. Next, in the init function, I added two lines which create, place, and anchor the help button on the screen.*
Before:
After:

Issue193: Help Guide

---

GUI.py

Fixes #194 
When there is an error, a pop-up appears with error message and a button that takes the user to repository to file an issue.
Before, when the backend encounters an error, users are not immediately notified, and the only way to identify the issue is by manually inspecting the console output. To improve this, I added an error handling improvement makes this process easier and more intuitive.
A decorator global_error_handler is added to catch exceptions in methods and display the error pop-up. The decorator is applied to all methods in the mainGUI and audioMenu classes. The show_error_popup function creates a CTkToplevel window with an error message and a "File a Bug" button. The "File a Bug" button opens the …

Issue#194: Error handling improvements

---

GUI.py

Fixed the clear box button issue

fixed the button

---

GUI.py
audio.py

Fixes #220 
Previously, the play and pause would crash the app, now the app doesn't crash and the choppiness of the audio file is less heard. The issue of the choppiness still remains after 2 or 3 pause and plays however. The transcription button now does not crash the program when used after pausing and playing, however, its functionality is extremely slow in doing so now. 
**Why was it changed**
This main focus of this issue is to resolve the hindering bug that crashes the application. Currently they have been minorly fixed and still needs work. 
Transcribe functions were changed and the play and pause functions were changed to help fix part of the issue.

Issue 220 Transcription and Play/Pause Crashing Minorly Fixed

---

GUI.py
audio.py
components/audio_menu.py

Fixes #243 
*I modified the GUI by adding a button which, when clicked, displays the waveform plot of an uploaded audio file.*
*This change was made in order to prevent cluttering the GUI and to make sure that users would only see the plot if they chose to.*
*I added a line in the GUI in order to create a new button. I also added a new function to the GUI which handles the rendering and displaying of the plot. In addition, I modified the uploadAudio method in the audio_menu file to prevent the audio from being plotted automatically after uploading the audio.*

Adding a "Show Audio Graph" Button

---

DEVELOPER_GUIDE.md

*changed the developer guide to organize it in a structured way.*

updating developer_guide
