oss-slu/SpeechTranscription

GUI.py

I added code so that after the audio is done playing, the "Play" button will change back to "Play" instead of remaining "Stop." Before this change, you would still have to click "Stop" to set the button back to "Play" and then click "Play" again to use the feature, but now it automatically resets after the audio is finished playing. fixes #73 
Explanation for changes made:
I set self.playing equal to False after the while loop that played the audio ends, as the audio is not playing anymore so the button should no longer be active in the 'Play' state.
I set the button text back to 'Play' so that the user now knows that the program is no longer in the 'Play' state as self.playing is now set to False so if the user hits the button the audio will now begin to play.
I print 'audio ended' to …

Reset 'Play' button and self.playing state after the audio is finished playing

---

GUI.py

Fixes #49
Implemented threading in the transcribe function and a loading bar during the transcription process.
*This was done because transcription would cause the program to display that it was not responding, now it does not do this. The loading bar is implemented to further illustrate to the user that transcription is in progress*
*The way the transcribe button works was changed by linking it to the loading process which then calls the transcription process that starts the thread. In the transcription method, the GUI elements are added*
during transcription:
after transcription:

work in progress on issue_#49. added threading to transcription and also started on progress bar

---

README.md

Fixes #105 
I added a section in README.md that addresses how to use the executable if you have a Macbook or are running MacOS.
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I changed the README.md documentation to add a section that describes how to run the executable on MacOS.
The executable did not work at all on MacOS before I figured out how to get it to work after many hours of testing and trial and error. I now am adding this section so that if a future developer or user is on MacOS, they can run the executable.
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
The …

Added instructions for how to access executable and get it to run on MacOS - FIXES #105

---

audio.py

Fixes #111
My pull request did not go through on Monday and I wasn't paying attention so my apologies
*Added a try-catch block to catch the error and an error window when there is no default audio device set up properly*
*It was changed because on computers with no audio device it would throw an error without the end user knowing*
*simple modification to audio.py to add a try catch block. and then a statement to add a msgbox with tkinter*

started out trying to suppress input error

---

diarizationAndTranscription.py

Fixes #147
Placed whisper's import under the same statement as pyannote's so both of their warnings are suppressed on startup. I have not encountered this warning before, so I am unsure if my changes have worked 100%.
Whisper seems to be sending a similar deprecation warning as pyannote was doing in a previous issue. Suppressing it will continue to prevent confusion for future developers.
- Moved whisper's import statement under the catch_warnings() manager. (diarizationandtranscription.py line 5)
- The application still has full functionality on my end after the change was made.

Suppressing warnings for whisper on import

---

.gitignore
DEVELOPER_GUIDE.md
README.md
macos-setup.md
requirements.txt

Fixes #157 
* Added macos-setup.md file, which describes the steps for setting up MacOS developer environment.
* Added reference to the new markdown file in README.
* Removed the MacOS steps from the requirements.txt file.
* Updated the .gitignore file by adding venv/.
* The steps for MacOS setup were updated to be in order and listed everything that was missing and had to be downloaded.
* The prerequisites required for the environment were also mentioned to avoid any confusion.
* The steps in requirements.txt file for MacOS was out of order and did not work.
* The files were too large to be able to push so I had to add the virtual environment files to .gitignore.
* When troubleshooting the issues with setting up the …

Added macos-setup.md file and updated .gitignore

---

DEVELOPER_GUIDE.md

This PR fixes the following issue:
After following the developer guide on Mac OS and running the application, I get the following error in the terminal:
```
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
```
Updated the MacOS section of DEVELOPER_GUIDE.md to install ffmpeg with homebrew.
Without installing ffmpeg with homebrew, I was unable to record an audio.

Fix for MacOS RuntimeWarning: Couldn't find ffmpeg or avconv

---

tests/test_gui.py

Fixes #160 
I added unit tests to test button responsiveness of the upload/record buttons in a new file: test_gui.py. This file is under the tests/ directory.
This was added because the responsiveness issue with button-clicking was identified as being dependent on the Python version. Issues with buttons responding either very slowly or not at all was occurring on machines with a Python version older than 3.11.7. When upgrading to a Python version that is 3.11.7 or greater, the button responded as expected. By adding these tests, we can confirm that the buttons perform correctly when the application is being run in Python 3.11.7 or higher.
Created tests:
* invoke_upload_button_and_measure_time()
* invoke_record_button_and_measure_time()
* Implemented mocks for uploadAudio and recordAudio …

Unit Testing For Button Responsiveness

---

.github/workflows/release.yml

…releases whenever a merge to the main branch happens
Fixes #168 
*Added a release.yml file to the workflows folder in order to automate the creation of build releases with a merge to the main branch*
*Currently, there aren't any build releases being made when a merge to the main branch occurs. This .yml file is meant to help automate this process with each merge to the main.*
*I had to add a new file to the workflows folder in order to automate the process of build release creation. I had to include sections to ensure that this is compatible for both mac and windows as well as the python version required.*

Working on automating build releases for merges to the main

---

.github/workflows/macos-build.yml
.github/workflows/windows-build.yml

Fixes #169 
A new file was added: `check_dependency.py`. Additionally, a new line was added to the `create-executable.yml` file.
The new file checks if the end-user has Java and the NLTK library installed. If not, it should prompt them to the Java website to install Java, and if they do not have NLTK library installed it should prompt the needed command to install the library.
Within the .yml file, a new line was added specifically to create a new .exe file that the end-user would need to run to check if they have the required dependencies in order to run the program.
This was changed because currently, the end-user must manually install dependencies themselves, which can be complicated for a non-technical person. This code helps with making the program more user-friendly, specifically in …

Added Dependency Checker File to Check if End-User Has Needed Dependencies

---

.github/workflows/macos-build.yml
.github/workflows/release.yml
.github/workflows/windows-build.yml

Fixes #178
*Edited the file to omit the build steps since those are being taken care of by other build files now. The main focus of this file is to now create releases after pushes to the target (main) branch.*
*Builds were previously failing, now the focus of this file is to simply create releases on pushes to the main branch.*
*Removed build components and focusing on creating releases only. Event triggers were also added to create when workflows for mac and windows builds complete. The updated file checks to ensure that previous workflows have properly completed before creating the release. Artifacts are also now managed by downloading based on the success of the mac and windows workflows.*
**Screenshots that show …

Issue178 build test failures

---

tests/saltify_test.py

Fixes #171
Addressing issue 171, where before the test function is only set up to handle a single pair of input and output files, but now the function is adjusted so that it can detect all the input/output pairs in a given directory, as well as match the input/output pairs to avoid any mismatches and accurately compare results.
This was changed so that developers can run tests for a variety of input and output files that may be numbered differently, rather than only comparing the information provided by input1 and output1. 
These changes were made by adjusting the saltify_test.py file, specifically the test function test_compare_input_with_output(self).

Support for multiple input and output files in satlify_test.py

---

GUI.py

Fixes #195 
*In the GUI, I changed the white background of the images to now be transparent, making the background be the same color of the lock/unlock/clear buttons.* 
*The previous look had a unappealing look when clicking on the lock/unlock/clear buttons. Now they are clean and isn't a visual clutter.*
**Here, describe the issue that you are fixing with this code, and why your code fixes it.**
*I created a function called scale_image for any new image and current images to always be scaled to 30x30 pixels (without the function, any image can be scaled to any number). The added configurations to the buttons makes the white background disappear because customtkinter.CTkImage, and before the changes it might have been because the image was …

Issue_#195

---

GUI.py
diarizationAndTranscription.py

Fixes #202 
The changes were made to the transcription functionality of the application, specifically in the diarizationAndTranscription.py file. The goal was to integrate synchronized timestamps into the transcribed text displayed in the transcription box.
The change was made to improve the readability and usability of the transcribed text. Previously, the transcription did not include timestamps, making it difficult for users to track when specific parts of the transcription occurred in the audio. By adding synchronized timestamps, users can now easily correlate the transcribed text with the corresponding time in the audio.
In diarizationAndTranscription.py, I added a new function formatTranscriptionWithTimestamps to …

Issue 202: Add synchronized timestamps to transcription lines

---

GUI.py

Fixes #185 
The change was a slider was now added to let users navigate through the audio file and be able see the duration of the audio when playing. The slider is at the bottom of the program and will move when the user hits play. 
This was changed so that the user can have a visual indicator of where they are in the audio file.  Additionally, allowing them to move through the audio file easily. 
By adding a slider at the bottom of the application, the user is able to move the circle back and forth to change where they are in the file and be able to see the progress they made. 
Additionally, there are some errors with test the scrubbing, but the timeline bar works fine
**Screenshots that show the changes (if …

185 implement interactive audio timeline

---

GUI.py

Fixes #212 
*I made edits to the GUI file in order to ensure that the upload and record audio buttons are disabled after the initial upload/record and are only enabled again if a new audio session is created. I also updated the help guide to include this information*
*The purpose for these changes is to ensure that there won't be any inconsistencies within audio sessions. My code works to lock and unlock the buttons accordingly.*
*I added lockItem and unlockItem statements to the recordAudio and uploadAudio functions as well as unlockItem statements to new_audio function in order to lock and unlock the Upload Audio and Record Audio buttons, such that they will only be unlocked at the start of a new audio session and …

Locking Upload and Record Audio Buttons

---

scripts/macOS_exec.sh

Fixes #214
I modified the macOS_exec.sh script. 
The script used absolute paths, making it non-portable and dependent on specific directory structures. By making the changes, the script is now portable by using relative paths.
I replaced absolute paths with relative paths based on the script's location and modified the pyinstaller command to use relative paths for --add-data and --add-binary options.

Relative Paths for Cross-Platform Execution

---

GUI.py

Fixes #218 
*I modified the GUI by replacing the text above the upload/record audio buttons with an editable textbox which has default titles depending on if the audio is uploaded or recorded but can still be edited.*
*This fix will allow for more clarity for the users to know which files they are working with as well as giving them more freedom to rename files generated during sessions.*
*In the GUI file, I removed the previous text field above the upload/record audio buttons and added a CTkEntry field in its place which is editable but has a default title depending on whether audio is uploaded or recorded.*
Before:
After:

Adding an Editable Textbox above Upload/Record Audio Buttons

---

GUI.py

Fixes #219
**Note**
This update is dependent on Issue #220, assuming the pausing and resuming playback feature is properly functioning.
I modified the GUI.py so that when a line in the transcription box is clicked, the audio playback is moved  to the corresponding time associated with the timestamp of that line. It is ensured the scrub bar (audio progress bar) updates accordingly.
This feature updates allows the user to easily navigate through the audio based on what line they are in the transcription box making it more interactive.
In GUI.py, I added a bind click event to transcription box which activates on_transcription_click() method. When a click occurs, it determines the line clicked, extracts the timestamp, …

Clickable Timestamps in Transcription Box for Audio Playback

---

GUI.py

Fixes #227 
*I updated the initial audio session flow by removing the existing "New Audio" button, and the subsequent pop-up window to name the session, with a "New Session" button that automatically directs the user to the main application page when clicked.*
*These changes were made to simplify the initial set-up after the app has launched and to organize the session naming process.*
*In the GUI file, I added a new_session method to the mainGUI class which generates a new session, titled in a Session <Number> - <Date> <Time> format. I also removed the pop-up dialog box which was previously used to name the session.*

Issue 227 - New Session Flow

---

components/audio_menu.py

Fixes #241 
Added color-coding to speaker labels and buttons in the labeling window to match the main transcription box's styling.
To make speakers visually distinguishable when selecting multiple lines and maintain consistency with the main interface.
By modifying the label display to use colored text and buttons, while keeping all existing functionality intact. I only made changes in audio_menu.py file.

Add speaker label colors in speaker label box

---

GUI.py
components/audio_menu.py

Fixes #236 
What was changed:
- The speaker labeling interface was updated by changing the default labels from "Speaker 1" and "Speaker 2" to "C" (for child) and "E" (for examiner).
- The interface now clearly reflects these changes in both the UI and the transcription export.
- Additionally, the speaker buttons in the transcription interface were color-coded to reflect each speaker's new label, making it easier for the user to identify the associated speaker.
Why was it changed:
- The original design, which used "Speaker 1" and "Speaker 2," didn’t align with SALT requirements, which specify the use of "C" and "E" for the child and examiner speakers, respectively.
- The update ensures that the application complies with standardized transcription practices, making it easier for users to …

Issue236 : Correct Speaker Label Titles

---

diarizationAndTranscription.py

Fixes #250 
I updated the parts of the code that create timestamps and match speakers — mainly the transcribe() function, diarizeAndTranscribe() function, and the formatting helpers. Timestamps now use exact times in milliseconds and are shown as minutes:seconds with proper formatting. I removed a built-in -2000 ms shift that made speaker times inaccurate, improved how text lines match their timestamps, and added a check that warns if timestamps end too early or don’t match the audio length.
Before, the timestamps were sometimes cut off early or didn’t line up with the audio because they were based on relative chunk times and included a fixed time shift. Using exact times fixes the early cutoff and makes timestamps match the real audio …

Fix #250: Fix Inaccurate Timestamps (Transcription & Playback Alignment)

---

README.md
requirements.txt

**This PR addresses the following CI/CD ticket: https://github.com/oss-slu/oss_cicd_automation/issues/1**
**What was investigated?**
- Checked Windows Event Logs for crash evidence. Initial Windows DCOM log entries (ContentDeliveryManager) were noise and unrelated.
- Reproduced the crash locally by running the packaged `.exe` from Command Prompt. That revealed Python runtime/DLL errors and file-not-found exceptions for package data files.
- Confirmed the app runs in a development environment with `python GUI.py` (so the crash is packaging and dependency-related).
1. Added comments to requirements.txt file, specifically for pattern and lightning fabric.
2. Created a section titled "Known Issues and Packaging Notes" in the README.md file describing why the .exe file …

Fix Windows .exe crash by adding missing data to PyInstaller build
